-- MySQL Script generated by MySQL Workbench
-- чт, 09-тра-2019 21:47:14 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus_station_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bus_station_db` ;

-- -----------------------------------------------------
-- Schema bus_station_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus_station_db` DEFAULT CHARACTER SET utf8 ;
USE `bus_station_db` ;

-- -----------------------------------------------------
-- Table `bus_station_db`.`cdl_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`cdl_classes` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`cdl_classes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` ENUM('B', 'C') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`buses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`buses` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`buses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `seat_amount` INT UNSIGNED NOT NULL,
  `cdl_class_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buses_1_idx` (`cdl_class_id` ASC),
  CONSTRAINT `fk_buses_1`
    FOREIGN KEY (`cdl_class_id`)
    REFERENCES `bus_station_db`.`cdl_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`employees` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `hire_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `phone` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_employees_1_idx` (`role_id` ASC),
  CONSTRAINT `fk_employees_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `bus_station_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`cities` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`cities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(32) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQUE_PAIR` (`city` ASC, `state` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`routes` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`routes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `departure_point_id` INT UNSIGNED NOT NULL,
  `destination_point_id` INT UNSIGNED NOT NULL,
  `distance` INT NOT NULL,
  `duration` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_routes_1_idx` (`departure_point_id` ASC),
  INDEX `fk_routes_2_idx` (`destination_point_id` ASC),
  CONSTRAINT `fk_routes_1`
    FOREIGN KEY (`departure_point_id`)
    REFERENCES `bus_station_db`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_routes_2`
    FOREIGN KEY (`destination_point_id`)
    REFERENCES `bus_station_db`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`schedule` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`schedule` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `route_id` INT UNSIGNED NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `bus_id` INT UNSIGNED NOT NULL,
  `driver_id` INT UNSIGNED NOT NULL,
  `admin_id` INT UNSIGNED NOT NULL,
  `status` ENUM('CREATED', 'CONFIRMED', 'ON_ROAD', 'ARRIVED') NOT NULL DEFAULT 'CREATED',
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_1_idx` (`bus_id` ASC),
  INDEX `fk_schedule_2_idx` (`route_id` ASC),
  INDEX `fk_schedule_3_idx` (`admin_id` ASC),
  INDEX `fk_schedule_4_idx` (`driver_id` ASC),
  CONSTRAINT `fk_schedule_1`
    FOREIGN KEY (`bus_id`)
    REFERENCES `bus_station_db`.`buses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_2`
    FOREIGN KEY (`route_id`)
    REFERENCES `bus_station_db`.`routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_3`
    FOREIGN KEY (`admin_id`)
    REFERENCES `bus_station_db`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_4`
    FOREIGN KEY (`driver_id`)
    REFERENCES `bus_station_db`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_station_db`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bus_station_db`.`drivers` ;

CREATE TABLE IF NOT EXISTS `bus_station_db`.`drivers` (
  `id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `experience_years` INT NOT NULL,
  `cdl_class_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`experience_years`),
  INDEX `fk_drivers_1_idx` (`employee_id` ASC),
  INDEX `fk_drivers_2_idx` (`cdl_class_id` ASC),
  CONSTRAINT `fk_drivers_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `bus_station_db`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_drivers_2`
    FOREIGN KEY (`cdl_class_id`)
    REFERENCES `bus_station_db`.`cdl_classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

